---
# tasks file for hfs
  - name: Install NFS client
    apt:
      name: nfs-common
      state: present      
      update_cache: yes

  - name: create nfs group-"{{ nfs_group }}" gid-"{{ nfs_gid }}"
    group:
      name: "{{ nfs_group }}"
      state: present
      gid: "{{ nfs_gid }}"

  - name: Check directory
    stat:
      path: "/{{ nfs_share_name }}"
    register: my_folder
 
  - name: Creates directory with group "{{ nfs_group }}"
    file:
      path: "/{{ nfs_share_name }}"
      state: directory
      group: "{{ nfs_group }}"
      mode: 2775
    when: my_folder.stat.exists == false

  - name: mount network share
    ansible.posix.mount:
      src: "{{ nfs_server_ip }}:/{{ nfs_share_name }}"
      path: "/{{ nfs_share_name }}"
      fstype: nfs
      opts: 'rw,sync'
      state: mounted
