---
# tasks file for hfs
  - name: Install NFS client
    apt:
      name: nfs-common
      state: present      
      update_cache: yes

  - name: create nfs group-"{{ nfs_group }}" gid-"{{ nfs_user_uid_gid }}"
    group:
      name: "{{ nfs_group }}"
      state: present
      gid: "{{ nfs_user_uid_gid }}"

  - name: create nfs user-"{{ nfs_client_user }}" uid-"{{ nfs_client_user_uid }}"
    user:
      name: "{{ nfs_client_user }}"
      uid: "{{ nfs_client_user_uid }}"
      group: "{{ nfs_group }}"
      state: present
      shell: /usr/sbin/nologin      # Defaults to /bin/bash
      system: yes             # Defaults to no
      createhome: no        # Defaults to yes

  - name: Check directory
    stat:
      path: "/{{ nfs_share_name }}"
    register: my_folder
 
  - name: Creates directory owner- "{{ nfs_client_user }}"-"{{ nfs_group }}"
    file:
      path: "/{{ nfs_share_name }}"
      state: directory
      owner: "{{ nfs_client_user }}"
      group: "{{ nfs_group }}"
      mode: 2775
    when: my_folder.stat.exists == false


  - name: mount network share
    ansible.posix.mount:
      src: "{{ nfs_server_ip }}:/{{ nfs_share_name }}"
      path: "/{{ nfs_share_name }}"
      fstype: nfs
      opts: 'rw,sync'
      state: mounted
