---
# tasks file for hfs
  - name: Install NFS server
    apt:
      name: nfs-kernel-server
      state: present      
      update_cache: yes

  - name: create nfs group
    group:
      name: "{{ nfs_group }}"
      state: present
      gid: "{{ nfs_gid }}"

  - name: Creates directory
    file:
      path: "/{{ nfs_share_name }}"
      state: directory
      group: "{{ nfs_group }}"
      mode: 0775
