---
# tasks file for transmission
  - name: Add repo transmission
    ansible.builtin.apt_repository:
      repo: ppa:transmissionbt/ppa

  - name: install transmission
    apt:
      pkg:
      - transmission-cli 
      - transmission-common 
      - transmission-daemon
      state: present
      update_cache: yes
    
  - name: stop transmission
    systemd:
      name: transmission-daemon
      state: stopped
      
  - name: set transmission uid
    user:
      name: debian-transmission
      uid: "{{ nfs_clients.transmission.uid }}"
      state: present
    notify: start transmission
