---
# tasks file for emby
  - name: Download Emby deb
    get_url:
      url: https://github.com/MediaBrowser/Emby.Releases/releases/download/4.7.8.0/emby-server-deb_4.7.8.0_amd64.deb
      dest: /tmp

  - name: Install Emby deb
    apt:
      deb: /tmp/emby-server-deb_4.7.8.0_amd64.deb